version: '3.8'

services:
  app:
    build:
      context: .  # Build from the Dockerfile in the current directory
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Maps port 80 in the container to port 80 on the host
    volumes:
      - .:/app  # Syncs the current directory with /app in the container
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    user: "${UID}:${GID}"
